name: plum-batch
home: https://github.com/hmcts/cnp-plum-batch
version: 0.0.7
description: HMCTS Plum batch (test application)
apiVersion: v2
dependencies:
  - name: job
    version: 0.7.8
    repository: 'oci://hmctspublic.azurecr.io/helm'
